#the maximum range sensor reading that will result in an obstacle being put into the costmap
obstacle_range: 2.5
#the range to which we will raytrace freespace given a sensor reading
raytrace_range: 3.0
#footprint: [[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]
robot_radius: 0.18
global_frame: map
robot_base_frame: robotino_base_link


#layer definitions
static_layer:
        map_topic: /map
        subscribe_to_updates: true

obstacle_layer:
        observation_sources: laser_scan_sensor
        laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}

inflation_layer:
        inflation_radius: 1.0

