global_costmap:
  global_frame: /map
  robot_base_frame: robotino_base_link
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5
  static_map: true
  rolling_window: false
  inflation_radius: 2.5
  resolution: 0.1

plugins:
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

